ipv6: false

geodata-mode: true
geodata-loader: standard
geo-auto-update: true
geox-url:
  geoip: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.dat"
  geosite: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat"
  mmdb: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/country.mmdb"
  asn: "https://github.com/xishang0128/geoip/releases/download/latest/GeoLite2-ASN.mmdb"
tcp-concurrent: true
unified-delay: true
keep-alive-interval: 30
find-process-mode: strict
global-client-fingerprint: chrome
mode: rule
log-level: info
external-ui-url: "https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip"
profile:
  store-selected: true
  store-fake-ip: true
dns:
  enable: true
  ipv6: true
  enhanced-mode: redir-host
  listen: 0.0.0.0:53
  nameserver-policy:
    "geosite:cn,private":
      - "https://dns.alidns.com/dns-query#h3=true"
      - "https://doh.pub/dns-query"
    "geosite:gfw":
      - "https://dns.google/dns-query#\U0001F680 节点选择"
      - "https://dns11.quad9.net/dns-query#\U0001F680 节点选择"
  nameserver:
    - "https://dns.alidns.com/dns-query#h3=true"
    - "https://doh.pub/dns-query"
  fallback:
    - "https://dns.google/dns-query#\U0001F680 节点选择"
    - "https://dns11.quad9.net/dns-query#\U0001F680 节点选择"
  fallback-filter:
    geoip: true
    geoip-code: CN
    geosite:
      - gfw
    ipcidr:
      - 240.0.0.0/4
    domain:
      - "+.google.com"
      - "+.facebook.com"
      - "+.youtube.com"
  default-nameserver:
    - 223.5.5.5
    - 119.29.29.29
sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  override-destination: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
    TLS:
      ports: [443, 5228, 8443]
    QUIC:
      ports: [443, 8443]
tun:
  enable: true
  stack: mixed
  device: utun
  auto-route: true
  auto-redirect: true
  auto-detect-interface: true
  strict-route: true
  dns-hijack:
    - tcp://any:53
