ipv6: false
geodata-mode: true
geodata-loader: standard
tcp-concurrent: true
unified-delay: true
keep-alive-interval: 1800
dns:
  enable: true
  ipv6: false
  prefer-h3: true
  enhanced-mode: redir-host
  listen: 0.0.0.0:53
  nameserver:
  - https://223.5.5.5/dns-query#h3=true
  - https://1.12.12.12/dns-query
  fallback:
  - https://8.8.8.8/dns-query
  - https://1.1.1.1/dns-query
  # default-nameserver:
  # - 223.5.5.5
  # - 119.29.29.29
  # proxy-server-nameserver:
  # - 223.5.5.5
  # - 119.29.29.29
sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
tun:
  enable: true
  stack: system
  device: utun
  auto-route: false
  auto-detect-interface: false
  dns-hijack:
  - tcp://any:53
profile:
  store-selected: true
  store-fake-ip: true
