ipv6: false
geodata-mode: true
geodata-loader: standard
tcp-concurrent: true
unified-delay: true
keep-alive-interval: 30
dns:
  enable: true
  ipv6: false
  enhanced-mode: redir-host
  listen: 0.0.0.0:53
  nameserver:
   - 'https://dns.alidns.com/dns-query#h3=true'
   - 'https://dns.pub/dns-query#h3=true'
  fallback:
   - 'https://8.8.8.8/dns-query'
   - 'https://208.67.220.220/dns-query'
  default-nameserver:
   - 223.5.5.5
   - 119.29.29.29
  # proxy-server-nameserver:
  # - 223.5.5.5
  # - 119.29.29.29
sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
tun:
  enable: true
  stack: system
  device: utun
  auto-route: false
  auto-detect-interface: false
  dns-hijack:
   - tcp://any:53
profile:
  store-selected: true
  store-fake-ip: true
