ipv6: false
geodata-mode: true
geodata-loader: standard
tcp-concurrent: true
unified-delay: true
keep-alive-interval: 30
find-process-mode: strict
global-client-fingerprint: chrome
profile:
  store-selected: true
  store-fake-ip: true
dns:
  enable: true
  ipv6: true
  enhanced-mode: redir-host
  listen: 0.0.0.0:53
  nameserver:
    - "https://dns.alidns.com/dns-query#h3=true"
    - "https://doh.pub/dns-query"
  fallback:
    - "https://8.8.8.8/dns-query#\U0001F680 节点选择"
    - "https://208.67.220.220/dns-query#\U0001F680 节点选择"
  nameserver-policy:
    "geosite:cn,private":
      - https://doh.pub/dns-query
      - https://dns.alidns.com/dns-query
  fallback-filter:
    geoip: true
    geoip-code: CN
    geosite:
      - gfw
    ipcidr:
      - 240.0.0.0/4
    domain:
      - "+.google.com"
      - "+.facebook.com"
      - "+.youtube.com"
  default-nameserver:
    - 223.5.5.5
    - 119.29.29.29
sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  override-destination: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
    TLS:
      ports: [443, 5228, 8443]
    QUIC:
      ports: [443, 8443]
tun:
  enable: true
  stack: system
  device: utun
  auto-route: true
  auto-detect-interface: true
  strict-route: true
  auto-redirect: false
  dns-hijack:
    - tcp://any:53
